admins/urls.py
"""
это модуль обеспечивающий работу пространства адресов приложения «админка»
"""
from django.urls import path
from admins.views import index, admin_users_update, admin_users_delete, admin_categorys_delete
from admins.views import admin_categorys_update, admin_products_update, admin_products_delete
# CBV
from admins.views import UserListView, UserCreateView, ProductCategoryListView
from admins.views import ProductsListView, ProductsCategoryCreateView, ProductsCreateView
app_name = 'admins'

urlpatterns = [
    path('', index, name = 'index'),
# управление пользователями
    path('users/', UserListView.as_view(), name='admin_users'),
    path('users-create/', UserCreateView.as_view(), name='admin_users_create'),
    path('users-update/<int:pk>/', admin_users_update, name='admin_users_update'),
    path('users-delete/<int:pk>/', admin_users_delete, name='admin_users_delete'),
# управление категориями
    path('categorys/', ProductCategoryListView.as_view(), name='admin_categorys'),
    path('categorys-create/', ProductsCategoryCreateView.as_view(), name='admin_categorys_create'),
    path('categorys-update/<int:key>/', admin_categorys_update, name = 'admin_categorys_update'),
    path('categirys-delete/<int:key>/', admin_categorys_delete, name = 'admin_categorys_delete'),
# управление товарами
    path('products/', ProductsListView.as_view(), name='admin_products'),
    path('products-create/', ProductsCreateView.as_view(), name='admin_products_create'),
    path('products-update/<int:key>/', admin_products_update, name = 'admin_products_update'),
    path('products-delete/<int:key>/', admin_products_delete, name = 'admin_products_delete'),
]

geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
import products.views as products
from products.views import index
from products.views import products

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', index, name='index'),
    path('products/', include('products.urls', namespace='products'), name='products'),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users'), name='users'),
    path('baskets/', include('baskets.urls', namespace='baskets'), name='baskets'),
    path('admins/', include('admins.urls', namespace = 'admins'), name='admins'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users.views import login, registration, logout, profile

app_name = 'users'

urlpatterns = [
    path('login/', login, name='login'),
    path('registration/', registration, name='registration'),
    path('logout/', logout, name='logout'),
    path('profile/', profile, name='profile'),
]

admins/templates/admins/admin-category-create.html
{% extends 'admins/base_template.html'%} {% load static %}

{% block content %}
    <main>
        <div class="container-fluid">
            <h1 class="mt-4">Новая категория товаров</h1>
            <form action="{% url 'admins:admin_categorys_create' %}" method="post">
                {% csrf_token %}
                <div class="form-row">
                    <div class="col-lg-12">
                        <div class="form-group">
                            <label class="small mb-1">Название</label>
                            {{form.name}}
                        </div>
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-lg-12">
                        <div class="form-group">
                            <label class="small mb-1">Описание</label>
                            {{form.description}}
                        </div>
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-lg-12" style="margin-top: 33px;">
                        <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                    </div>
                </div>
            </form>
        </div>
    </main>
{%endblock%}

admins/templates/admins/admin-category-read.html
{% extends 'admins/base_template.html'%}
{% load static %}

{% block content%}
<main>
    <div class="container-fluid">
        <h1 class="mt-4">Категории товаров</h1>
        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-table mr-1"></i>
                Категории
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>Название категории</th>
                            <th>Описание</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for category in object_list %}
                        <tr>
                            <td><a href="{% url 'admins:admin_categorys_update' category.id %}" style="color: dodgerblue">{{category.name}}</a></td>
                            <td>{{category.description}}</td>
                        </tr>
                        {%endfor%}
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="card-footer">
                <a href="{% url 'admins:admin_categorys_create'%}">
                    <button class="btn btn-success">Добавить категорию</button>
                </a>
            </div>
        </div>
    </div>
</main>
{%endblock%}

admins/templates/admins/admin-category-update-delete.html
{% extends 'admins/base_template.html'%}
{% load static %}

{% block content%}
<main>
    <div class="container-fluid">
        <h1 class="mt-4">Изменение категории | {{selected_category.name}}</h1>
        <div class="card-body">
            <form action="{% url 'admins:admin_categorys_update' selected_category.id%}" method="POST" >
                {% csrf_token %}
                <div class="form-row">
                    <div class="col-lg-12">
                        <div class="form-group">
                            <label class="small mb-1">Имя</label>
                            {{form.name}}
                        </div>
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-lg-12">
                        <div class="form-group">
                            <label class="small mb-1">Фамилия</label>
                            {{form.description}}
                        </div>
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-lg-12" style="margin-top: 33px;">
                        <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                    </div>
                </div>
            </form>
            <div class="row">
                <div class="col-lg-12" style="margin-top: 33px;">
                        <a class="btn btn-danger btn-block" href = "{% url 'admins:admin_categorys_delete' selected_category.id %}" >Удалить</a>
                </div>
            </div>
        </div>
    </div>
</main>
{%endblock%}

admins/templates/admins/admin-products-create.html
{% extends 'admins/base_template.html'%} {% load static %}

{% block content %}
    <main>
        <div class="container-fluid">
            <h1 class="mt-4">Новый товар</h1>
            <form action="{% url 'admins:admin_products_create' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                    <table width="100%" cellspacing="0">
                        <tbody>
                            <tr>
                                <td>Название</td>
                                <td>{{form.name}}</td>
                            </tr>
                            <tr>
                                <td>Изображение</td>
                                <td>{{form.image}}</td>
                            </tr>
                            <tr>
                                <td>Описание</td>
                                <td>{{form.description}}</td>
                            </tr>
                            <tr>
                                <td>Категория</td>
                                <td>{{form.category}}</td>
                            </tr>
                            <tr>
                                <td>Цена</td>
                                <td>{{form.price}}</td>
                            </tr>
                            <tr>
                                <td>Количество</td>
                                <td>{{form.quantity}}</td>
                            </tr>
                        </tbody>
                    </table>
                <div class="form-row">
                    <div class="col-lg-12" style="margin-top: 33px;">
                        <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                    </div>
                </div>
            </form>
        </div>
    </main>
{%endblock%}

admins/templates/admins/admin-products-read.html
{% extends 'admins/base_template.html'%}
{% load static %}

{% block content%}
<main>
    <div class="container-fluid">
        <h1 class="mt-4">Ассортимент</h1>
        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-table mr-1"></i>
                Товары
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>Товар</th>
                            <th>Описание</th>
                            <th>Категория</th>
                            <th>Цена</th>
                            <th>Кол-во</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for product in object_list %}
                        <tr>
                            <td><a href="{% url 'admins:admin_products_update' product.id %}" style="color: dodgerblue">{{product.name}}</a></td>
                            <td>{{product.description}}</td>
                            <td>{{product.category}}</td>
                            <td>{{product.price}}</td>
                            <td>{{product.quantity}}</td>
                        </tr>
                        {%endfor%}
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="card-footer">
                <a href="{% url 'admins:admin_products_create'%}">
                    <button class="btn btn-success">Добавить товар</button>
                </a>
            </div>
        </div>
    </div>
</main>
{%endblock%}

admins/templates/admins/admin-products-update-delete.html
{% extends 'admins/base_template.html'%}
{% load static %}

{% block content%}
<main>
    <div class="container-fluid">

        <h1 class="mt-4">Изменение категории | {{selected_product.name}}</h1>
        <div class="card-body">
            <form action="{% url 'admins:admin_products_update' selected_product.id%}" method="POST"  enctype="multipart/form-data">
                {% csrf_token %}
                    <table width="100%" cellspacing="0">
                        <tbody>
                            <tr>
                                <td>Название</td>
                                <td>{{form.name}}</td>
                            </tr>
                            <tr>
                                <td>Изображение</td>
                                <td>{{form.image}}</td>
                            </tr>
                            <tr>
                                <td>Описание</td>
                                <td>{{form.description}}</td>
                            </tr>
                            <tr>
                                <td>Категория</td>
                                <td>{{form.category}}</td>
                            </tr>
                            <tr>
                                <td>Цена</td>
                                <td>{{form.price}}</td>
                            </tr>
                            <tr>
                                <td>Количество</td>
                                <td>{{form.quantity}}</td>
                            </tr>
                        </tbody>
                    </table>
                <div class="form-row">
                    <div class="col-lg-12" style="margin-top: 33px;">
                        <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                    </div>
                </div>
            </form>
            <div class="row">
                <div class="col-lg-12" style="margin-top: 33px;">
                        <a class="btn btn-danger btn-block" href = "{% url 'admins:admin_products_delete' selected_product.id %}" >Удалить</a>
                </div>
            </div>
        </div>
    </div>
</main>
{%endblock%}

admins/templates/admins/admin-users-create.html
{% extends 'admins/base_template.html'%} {% load static %}

{% block content %}
    <main>
        <div class="container-fluid">
            <h1 class="mt-4">Создание пользователя</h1>
            <form action="{% url 'admins:admin_users_create' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-row">
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="small mb-1">Имя</label>
                            {{form.first_name}}
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="small mb-1">Фамилия</label>
                            {{form.last_name}}
                        </div>
                    </div>
                </div>
                <div class="form-row mb-2">
                    <div class="col-lg-12">
                        <div class="custom-file">
                            {{ form.image }}
                            <label class="custom-file-label">
                                Выберите изображение
                            </label>
                        </div>
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-lg-6">
                        <label class="small mb-1">Имя пользователя</label>
                        {{form.username}}
                    </div>
                    <div class="col-lg-6">
                        <label class="small mb-1">Адрес электронной почты</label>
                        {{form.email}}
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-lg-6">
                        <label class="small mb-1">Пароль</label>
                        {{form.password1}}
                    </div>
                    <div class="col-lg-6">
                        <label class="small mb-1">Повторите пароль</label>
                        {{form.password2}}
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-lg-12" style="margin-top: 33px;">
                        <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                    </div>
                </div>
            </form>
        </div>
    </main>
{%endblock%}

admins/templates/admins/admin-users-read.html
{% extends 'admins/base_template.html'%}
{% load static %}

{% block content%}
<main>
    <div class="container-fluid">
        <h1 class="mt-4">Пользователи</h1>
        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-table mr-1"></i>
                Пользователи
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>Имя пользователя</th>
                            <th>Имя</th>
                            <th>Фамилия</th>
                            <th>Адрес эл. почты</th>
                            <th>Персонал сайта</th>
                            <th>Активный</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for us in object_list %}
                        <tr>
                            <td><a href="{% url 'admins:admin_users_update' us.id %}" style="color: dodgerblue">{{us.username}}</a></td>
                            <td>{{us.first_name}}</td>
                            <td>{{us.last_name}}</td>
                            <td>{{us.email}}</td>
                            {%if us.is_staff%}
                                <td class="text-center"><i class="fas fa-check-circle"></i></td>
                            {%else%}
                                <td class="text-center"><i class="fas fa-times-circle"></i></td>
                            {%endif%}
                            {%if us.is_active%}
                                <td class="text-center"><i class="fas fa-check-circle"></i></td>
                            {%else%}
                                <td class="text-center"><i class="fas fa-times-circle"></i></td>
                            {%endif%}
                        </tr>
                        {%endfor%}
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="card-footer">
                <a href="{% url 'admins:admin_users_create'%}">
                    <button class="btn btn-success">Создать пользователя</button>
                </a>
            </div>
        </div>
    </div>
</main>
{%endblock%}

admins/templates/admins/admin-users-update-delete.html
{% extends 'admins/base_template.html'%}
{% load static %}

{% block content%}
<main>
    <div class="container-fluid">
        <h1 class="mt-4">Редактирование пользователя | {{selected_user.username}}</h1>
        <div class="card-body">
            <form action="{% url 'admins:admin_users_update' selected_user.id%}" method="POST" >
                {% csrf_token %}
                <div class="form-row">
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="small mb-1">Имя</label>
                            {{form.first_name}}
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="small mb-1">Фамилия</label>
                            {{form.last_name}}
                        </div>
                    </div>
                </div>
                <div class="form-row mb-2">
                    <div class="col-lg-12">
                        <div class="custom-file">
                            {{form.image}}
                            <label class="custom-file-label">Выберите изображение</label>
                        </div>
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-lg-6">
                        <label class="small mb-1">Имя пользователя</label>
                        {{form.username}}
                    </div>
                    <div class="col-lg-6">
                        <label class="small mb-1">Адрес электронной почты</label>
                        {{form.email}}
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-lg-12" style="margin-top: 33px;">
                        <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                    </div>
                </div>
            </form>
            <div class="row">
                <div class="col-lg-12" style="margin-top: 33px;">
                    {% if selected_user.is_active%}
                        <a class="btn btn-danger btn-block" href = "{% url 'admins:admin_users_delete' selected_user.id %}" >Деактивировать</a>
                    {% else %}
                        <a class="btn btn-danger btn-block" href = "{% url 'admins:admin_users_delete' selected_user.id %}" >Активировать</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</main>
{%endblock%}

admins/templates/admins/base_template.html
{% load static %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>{{title}}</title>
    <link href="{% static '/css/auth-admin.css' %}" rel="stylesheet"/>
    <link href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css" rel="stylesheet"
          crossorigin="anonymous"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js"
            crossorigin="anonymous"></script>
</head>
<body class="sb-nav-fixed">
<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
    <a class="navbar-brand" href="{%url 'admins:index'%}">GeekShop</a>
    <button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#"><i class="fas fa-bars"></i>
    </button>
    <!-- Navbar Search-->
    <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
        <div class="input-group">
            <input class="form-control" type="text" placeholder="Поиск..." aria-label="Search"
                   aria-describedby="basic-addon2"/>
            <div class="input-group-append">
                <button class="btn btn-primary" type="button"><i class="fas fa-search"></i></button>
            </div>
        </div>
    </form>
    <!-- Navbar-->
    <ul class="navbar-nav ml-auto ml-md-0">
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown"
               aria-haspopup="true" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="{%url 'users:logout'%}">Logout</a>
            </div>
        </li>
    </ul>
</nav>
<div id="layoutSidenav">
    <div id="layoutSidenav_nav">
        <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
            <div class="sb-sidenav-menu">
                <div class="nav">
                    <div class="sb-sidenav-menu-heading">Приложения</div>
                    <a class="nav-link" href="{%url 'admins:admin_users'%}">
                        <div class="sb-nav-link-icon">
                            <i class="fas fa-users"></i>
                        </div>
                        Пользователи
                    </a>
                    <a class="nav-link" href="{%url 'admins:admin_categorys'%}">
                        <div class="sb-nav-link-icon">
                            <i class="fas fa-shopping-basket"></i>
                        </div>
                        Категории
                    </a>
                    <a class="nav-link" href="{%url 'admins:admin_products'%}">
                        <div class="sb-nav-link-icon">
                            <i class="fas fa-tshirt"></i>
                        </div>
                        Товары
                    </a>
                </div>
            </div>
            <div class="sb-sidenav-footer"></div>
        </nav>
    </div>
    <div id="layoutSidenav_content">
        {% block content %} {%endblock%}
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; GeekShop ))</div>
                </div>
            </div>
        </footer>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        crossorigin="anonymous"></script>
<script src="{% static '/js/auth-admin.js'%}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>
<script src="{% static '/js/datatable.js'%}"></script>
</body>
</html>

admins/templates/admins/index.html
{% extends 'admins/base_template.html'%}
{% load static %}

{% block content%}
        <main>
            <div class="container-fluid">
                <h1 class="mt-4">Административная панель</h1>
            </div>
        </main>
{% endblock%}